on:
  workflow_call:
    inputs:
      upload:
        required: true
        type: boolean

defaults:
  run:
    shell: bash

jobs:
  conda-build:
    runs-on: ubuntu-latest
    container:
      image: condaforge/mambaforge
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install mambabuild
        run: mamba install -c conda-forge boa
      - name: Build Frigate package
        run: conda mambabuild conda/recipes/frigate --output-folder /tmp/frigate-bld
      - name: Upload to Anaconda
        if: inputs.upload == true
        run: |
          mamba install -c conda-forge anaconda-client
          RAPIDS_CONDA_TOKEN=${{ secrets.CONDA_RAPIDSAI_NIGHTLY_TOKEN }}
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            RAPIDS_CONDA_TOKEN=${{ secrets.CONDA_RAPIDSAI_TOKEN }}
          fi
          anaconda -t "${RAPIDS_CONDA_TOKEN}" upload --skip-existing --no-progress /tmp/frigate-bld/noarch/*.tar.bz2
  wheel-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools twine
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: Upload to PyPI
        if: inputs.upload == true
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.RAPIDSAI_PYPI_TOKEN }}
